warnings_are_errors: false
language: python
python:
  - 3.5
  - 3.6
  - 3.7  
before_install:
  - pip install cython
  - git clone https://github.com/iogiul/starhalo_inspector.git
  - cd starhalo_inspector 
  - python setup.py install
  - cd ..
  - git clone https://github.com/iogiul/roteasy.git
  - cd roteasy
  - python setup.py install
  - cd ..
  - pip install astro-gala
install:
  - pip install .
script: pytest
